package com.acme.triangle.predicate;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

/**
 * Drives {@link Predicates} against the cross-language oracle
 * {@code contract/predicates.txt} (generated by the C reference's
 * predicate_oracle.c). Each line is one case; the Java predicate must reproduce
 * the recorded exact sign, including the near-degenerate cases.
 */
class PredicatesTest {

    private static final String ORACLE = "/contract/predicates.txt";

    @TestFactory
    List<DynamicTest> matchesOracleSigns() {
        List<DynamicTest> tests = new ArrayList<>();
        int line = 0;
        for (String raw : readOracle()) {
            line++;
            String s = raw.trim();
            if (s.isEmpty() || s.startsWith("#")) {
                continue;
            }
            String[] t = s.split("\\s+");
            String kind = t[0];
            final int lineNo = line;

            if ("orient2d".equals(kind)) {
                double ax = d(t[1]), ay = d(t[2]), bx = d(t[3]), by = d(t[4]),
                        cx = d(t[5]), cy = d(t[6]);
                int expected = Integer.parseInt(t[7]);
                tests.add(DynamicTest.dynamicTest("orient2d L" + lineNo, () ->
                        assertThat(Predicates.orient2d(ax, ay, bx, by, cx, cy))
                                .as("orient2d %s", s)
                                .isEqualTo(expected)));
            } else if ("incircle".equals(kind)) {
                double ax = d(t[1]), ay = d(t[2]), bx = d(t[3]), by = d(t[4]),
                        cx = d(t[5]), cy = d(t[6]), dx = d(t[7]), dy = d(t[8]);
                int expected = Integer.parseInt(t[9]);
                tests.add(DynamicTest.dynamicTest("incircle L" + lineNo, () ->
                        assertThat(Predicates.incircle(ax, ay, bx, by, cx, cy, dx, dy))
                                .as("incircle %s", s)
                                .isEqualTo(expected)));
            } else {
                throw new IllegalStateException("unknown predicate '" + kind
                        + "' at line " + lineNo);
            }
        }
        assertThat(tests).as("oracle cases parsed").isNotEmpty();
        return tests;
    }

    private static double d(String token) {
        return Double.parseDouble(token);
    }

    private List<String> readOracle() {
        try (InputStream in = getClass().getResourceAsStream(ORACLE)) {
            if (in == null) {
                throw new IllegalStateException("missing test resource " + ORACLE);
            }
            try (BufferedReader r = new BufferedReader(
                    new InputStreamReader(in, StandardCharsets.UTF_8))) {
                List<String> lines = new ArrayList<>();
                String l;
                while ((l = r.readLine()) != null) {
                    lines.add(l);
                }
                return lines;
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
